### ISSUE TITLE
CPU Code review

### ISSUE THREAD

**Issue by Dimanteo** [quaiion/DEPA#1]
* Убрать дублирующийся код getFileSize(). Вынести общие функции в отдельный файл и включать его через .h
* Порезать гигантские функции в ассемблере на функции поменьше. Ориентироваться можно на 80-110 символов в строке
* Проверять сигнатуру
* По-хорошему, каждая программа должна иметь .h + .cpp. И еще должен быть общий для всех хедер. Также общие функции следует вынести в отдельный .c файл. Чтобы скомпилировать прогу из нескольких .c фалов с общими хедерами надо сделать `g++ main.cpp stack.cpp cpu.cpp puk.cpp hruk.cpp"
* Нет дефайнов и кодогенерации ((

**Comment by quaiion** [comment]
я все слелол
